---
# tasks file for Debian_Cloning
 - name: Installing Debian GIT
   apt:
     name: git
     state: latest

 - name: Cloning Prelim-Exam Repository Debian
   git:
     repo: '{{ prelim_exam }}'
     dest: ./prelim-exam
     version: prelim-exam
